### ISSUE TITLE
WalkThrough

### ISSUE THREAD

**Issue by fedeniko** [Mindgreppers/lifemaker#93]
[https://atman45.wordpress.com/lifemaker/](url)

WalkThrough with 5 onboarding screens.

**Comment by mastersilv3r** [comment]
On Mon, May 9, 2016 at 10:18 AM, fedeniko notifications@github.com wrote:

> https://atman45.wordpress.com/lifemaker/ http://url

Food for thought:

Consider changing vidya to liberation (when people will feel liberated, the
reason for liberation is some gnana that they have gained)

Knowledge/information can be perhaps put into artha

liberation == self realization/ultimate life
artha == resources/skills/gnana
kama= fulfillment of desires/enjoyment/bliss
dharma=duty/ethos

# 

_Driven by the forces of love, the fragments of the world seek each other
so that the World may come into being._

World is already in the being. It is becoming. So I do not get this
statement. It is without a simple/direct meaning.

# 

you can meet new friends, learn about life, and grow as a person while
helping the world become a better place.
Meeting new friends is cliche. For facebook etc.
Here we have to focus on meeting open minded seekers of
change/improvement...

Learn about life, meet other open minded seekers, grow as a person and be
fulfilled while shaping a better world!

# 

World ethos
Replace generosity with Compassion

Open MInd
We advocate the mindful consideration of all perspectives and a humble
respect for every difference in belief. Without such tolerance and humility
no peaceful coexistence is possible.

We advocate the mindful consideration of all perspectives and and humble
respect for every difference in opinion or belief. Peaceful co-existence is
possible only with acceptance and humility. Also, in being open we open
ourselves to new and interesting possibilities.

Non-violence
We need to discuss when is violence ok? Eating meat? Culling monkeys when
they are destroying your farm every time? Protecting against someone who is
trying to kill you? Is that violence permitted?

# 

Holywood

Instead of "is" say "will be" because it is not decentralized today. We can
say it will be once the network takes a critical mass.

Emphasize more on the 1 holywood given with thanks. So that people can
immediately connect that thanks is a way to earn karma and wood too!

**Comment by fedeniko** [comment]
Walkthrough with 7 onboarding screens
[https://atman45.wordpress.com/lifemaker/]

**Comment by mastersilv3r** [comment]
Little edits needed and we are good.

**Comment by fedeniko** [comment]
:)

**Comment by fedeniko** [comment]
https://lifemakersite.wordpress.com/
